// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_STRUCT_PYOBJECT_H_
#define _BEHAVIAC_STRUCT_PYOBJECT_H_

#include "behaviac/agent/agent.h"
#include "pyscript/scriptobject.h"


namespace behaviac
{
	struct pyObject
	{
		PyObject* _pPyObject;
	};
}


#endif // _BEHAVIAC_STRUCT_PYOBJECT_H_
