// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../behaviac_types.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM_EX(behaviac::FightType, FightType)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO_EX(L"FightType", L"");

	BEHAVIAC_ENUM_ITEM_EX(behaviac::ENTITY_STATE_FREE, "ENTITY_STATE_FREE");
	BEHAVIAC_ENUM_ITEM_EX(behaviac::ENTITY_STATE_DEAD, "ENTITY_STATE_DEAD");
	BEHAVIAC_ENUM_ITEM_EX(behaviac::ENTITY_STATE_REST, "ENTITY_STATE_REST");
	BEHAVIAC_ENUM_ITEM_EX(behaviac::ENTITY_STATE_FIGHT, "ENTITY_STATE_FIGHT");
}
BEHAVIAC_END_ENUM_EX()

