// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_behaviac_KbeAgentBase_callPyFunc(Agent* self, behaviac::string funcName) { ((behaviac::KbeAgentBase*)self)->_Execute_Method_<behaviac::METHOD_TYPE_behaviac_KbeAgentBase_callPyFunc, void, behaviac::string >(funcName); }
	inline void FunctionPointer_behaviac_KbeAgentBase_LogMessage(char* param0) { behaviac::KbeAgentBase::LogMessage(param0); }
	inline void FunctionPointer_behaviac_Monster_callPyFunc(Agent* self, behaviac::string funcName) { ((behaviac::KbeAgentBase*)self)->_Execute_Method_<behaviac::METHOD_TYPE_behaviac_KbeAgentBase_callPyFunc, void, behaviac::string >(funcName); }
	inline void FunctionPointer_behaviac_Monster_hello(Agent* self) { ((behaviac::Monster*)self)->hello(); }
	inline void FunctionPointer_behaviac_Monster_LogMessage(char* param0) { behaviac::Monster::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
