// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_BEHAVIAC_MONSTER_H_
#define _BEHAVIAC_BEHAVIAC_MONSTER_H_

#include "behaviac_headers.h"

#include "KbeAgentBase.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT


	///<<< END WRITING YOUR CODE

namespace behaviac
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

	class Monster : public behaviac::KbeAgentBase
///<<< BEGIN WRITING YOUR CODE Monster
		///<<< END WRITING YOUR CODE
	{
	public:
		Monster();
		virtual ~Monster();

		BEHAVIAC_DECLARE_AGENTTYPE(behaviac::Monster, behaviac::KbeAgentBase)

		public: void hello();

///<<< BEGIN WRITING YOUR CODE CLASS_PART



				  ///<<< END WRITING YOUR CODE
	};

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

///<<< END WRITING YOUR CODE
}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
